/**
 * Demo-history seed: populates the app with ~6 months of believable
 * procurement activity so every role's screens (dashboard charts, queues,
 * All Requests, POs, Reports, Audit Trail) have real volume behind them.
 *
 * Everything is generated by walking each request through the SAME state
 * machine the app enforces (submit -> division -> finance -> PO -> delivered
 * -> closed, with rejections / returns / withdrawals along the way), writing
 * matching workflow_history + audit_log rows at each step. So the demo data
 * is indistinguishable from data created by clicking through the UI - the
 * audit trail, timelines and numbering all line up.
 *
 * Deterministic: a fixed PRNG seed + fixed row IDs. Re-running is a no-op
 * once seeded. Pass --reset to delete the generated rows and regenerate them
 * relative to today (handy before a demo so "this week" charts look fresh).
 *
 * Requires the base seed first:  npm run db:seed
 * Run with:                      npm run db:seed:demo  [-- --reset]
 */
import "dotenv/config";
import bcrypt from "bcryptjs";
import { inArray, like, sql as dsql } from "drizzle-orm";
import { db, sql } from "./index";
import {
  users,
  userCompanyAccess,
  userDivisionAccess,
  userRoles,
  vendors,
  purchaseRequests,
  purchaseOrders,
  workflowHistory,
  auditLog,
  companySequences,
} from "./schema";
import * as ids from "./ids";

// ---------- deterministic randomness ----------
function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(20260928);
const between = (min: number, max: number) => min + rand() * (max - min);
const int = (min: number, max: number) => Math.floor(between(min, max + 1));
const pick = <T,>(arr: readonly T[]): T => arr[Math.floor(rand() * arr.length)];
const chance = (p: number) => rand() < p;
const HOUR = 3600_000;
const DAY = 24 * HOUR;

const uid = (prefix: string, n: number) => `${prefix}-0000-0000-0000-${String(n).padStart(12, "0")}`;

// ---------- extra colleagues ----------
// The six logins on the sign-in page stay the primary demo accounts; these
// fill out the org so lists, activity feeds and the approval chain feel
// like a real company rather than one employee and one manager.
const U = {
  KABIR: uid("41000000", 1),
  ANANYA: uid("41000000", 2),
  VIKRAM: uid("41000000", 3),
  SANA: uid("41000000", 4),
  DEV: uid("41000000", 5),
  ISHAAN: uid("41000000", 6),
  NISHA: uid("41000000", 7),
};

const EXTRA_USERS = [
  { id: U.KABIR, name: "Kabir Das", email: "kabir@vendra.demo", company: ids.COMPANY_KIGM_ID, division: ids.DIVISION_PLANT_OPS_ID, manager: false },
  { id: U.ANANYA, name: "Ananya Rao", email: "ananya@vendra.demo", company: ids.COMPANY_KIGM_ID, division: ids.DIVISION_QUALITY_ID, manager: false },
  { id: U.VIKRAM, name: "Vikram Joshi", email: "vikram@vendra.demo", company: ids.COMPANY_KIGM_ID, division: ids.DIVISION_QUALITY_ID, manager: true },
  { id: U.SANA, name: "Sana Qureshi", email: "sana@vendra.demo", company: ids.COMPANY_KIGT_ID, division: ids.DIVISION_IMPORT_DESK_ID, manager: false },
  { id: U.DEV, name: "Dev Malhotra", email: "dev@vendra.demo", company: ids.COMPANY_KIGT_ID, division: ids.DIVISION_IMPORT_DESK_ID, manager: true },
  { id: U.ISHAAN, name: "Ishaan Bose", email: "ishaan@vendra.demo", company: ids.COMPANY_KIGT_ID, division: ids.DIVISION_DOMESTIC_SALES_ID, manager: false },
  { id: U.NISHA, name: "Nisha Menon", email: "nisha@vendra.demo", company: ids.COMPANY_KIGT_ID, division: ids.DIVISION_DOMESTIC_SALES_ID, manager: true },
];

// ---------- extra vendors ----------
const V = {
  BHARAT_SAFETY: uid("51000000", 1),
  APEX_LUBES: uid("51000000", 2),
  NIMBUS_KIGM: uid("51000000", 3),
  COASTAL_FREIGHT: uid("51000000", 4),
  SUNRISE_PACK: uid("51000000", 5),
  NIMBUS_KIGT: uid("51000000", 6),
};

const EXTRA_VENDORS = [
  { id: V.BHARAT_SAFETY, companyId: ids.COMPANY_KIGM_ID, name: "Bharat Safety Supplies", category: "Safety", contactName: "Ramesh Kulkarni", contactEmail: "sales@bharatsafety.example" },
  { id: V.APEX_LUBES, companyId: ids.COMPANY_KIGM_ID, name: "Apex Industrial Lubricants", category: "Consumables", contactName: "Farah Sheikh", contactEmail: "orders@apexlubes.example" },
  { id: V.NIMBUS_KIGM, companyId: ids.COMPANY_KIGM_ID, name: "Nimbus IT Solutions", category: "IT", contactName: "Karthik Iyer", contactEmail: "enterprise@nimbusit.example" },
  { id: V.COASTAL_FREIGHT, companyId: ids.COMPANY_KIGT_ID, name: "Coastal Freight Logistics", category: "Logistics", contactName: "Joseph D'Souza", contactEmail: "bookings@coastalfreight.example" },
  { id: V.SUNRISE_PACK, companyId: ids.COMPANY_KIGT_ID, name: "Sunrise Packaging", category: "Packaging", contactName: "Pooja Agarwal", contactEmail: "pooja@sunrisepack.example" },
  { id: V.NIMBUS_KIGT, companyId: ids.COMPANY_KIGT_ID, name: "Nimbus IT Solutions", category: "IT", contactName: "Karthik Iyer", contactEmail: "enterprise@nimbusit.example" },
];

// ---------- what each division buys ----------
type Item = { category: string; desc: string; qty: [number, number]; unit: [number, number]; vendor: string };

const CATALOG: Record<string, Item[]> = {
  [ids.DIVISION_PLANT_OPS_ID]: [
    { category: "Raw Materials", desc: "Mild steel sheets, 2 mm (per tonne)", qty: [2, 7], unit: [58000, 66000], vendor: ids.VENDOR_STEELCORP_ID },
    { category: "Raw Materials", desc: "EN8 round bars, 40 mm (per tonne)", qty: [1, 5], unit: [61000, 70000], vendor: ids.VENDOR_STEELCORP_ID },
    { category: "Equipment", desc: "Carbide end mill set, 6-piece", qty: [4, 20], unit: [3800, 6200], vendor: ids.VENDOR_PRECISION_TOOLS_ID },
    { category: "Equipment", desc: "Pneumatic torque wrench", qty: [2, 6], unit: [18000, 26000], vendor: ids.VENDOR_PRECISION_TOOLS_ID },
    { category: "Maintenance", desc: "Conveyor belt replacement, Line 2", qty: [1, 2], unit: [85000, 140000], vendor: ids.VENDOR_PRECISION_TOOLS_ID },
    { category: "Safety", desc: "Steel-toe safety shoes (pair)", qty: [20, 80], unit: [1400, 2100], vendor: V.BHARAT_SAFETY },
    { category: "Safety", desc: "Welding helmets, auto-darkening", qty: [6, 20], unit: [3200, 4800], vendor: V.BHARAT_SAFETY },
    { category: "Consumables", desc: "Hydraulic oil ISO VG 68 (210 L drum)", qty: [2, 8], unit: [21000, 27000], vendor: V.APEX_LUBES },
    { category: "Consumables", desc: "Cutting coolant concentrate (20 L)", qty: [10, 30], unit: [2600, 3400], vendor: V.APEX_LUBES },
  ],
  [ids.DIVISION_QUALITY_ID]: [
    { category: "Equipment", desc: "Digital vernier calipers, 0-200 mm", qty: [5, 15], unit: [4200, 7500], vendor: ids.VENDOR_PRECISION_TOOLS_ID },
    { category: "Equipment", desc: "Surface roughness tester", qty: [1, 1], unit: [145000, 210000], vendor: ids.VENDOR_PRECISION_TOOLS_ID },
    { category: "Equipment", desc: "Calibration gauge block set", qty: [1, 3], unit: [38000, 56000], vendor: ids.VENDOR_PRECISION_TOOLS_ID },
    { category: "IT", desc: "Rugged tablets for line inspection", qty: [3, 8], unit: [32000, 45000], vendor: V.NIMBUS_KIGM },
    { category: "IT", desc: "SPC software licence (annual)", qty: [2, 6], unit: [18000, 24000], vendor: V.NIMBUS_KIGM },
    { category: "Safety", desc: "Lab safety goggles", qty: [20, 60], unit: [350, 700], vendor: V.BHARAT_SAFETY },
  ],
  [ids.DIVISION_IMPORT_DESK_ID]: [
    { category: "Trading", desc: "HDPE granules, film grade (per MT)", qty: [2, 5], unit: [72000, 88000], vendor: ids.VENDOR_ORIENT_IMPORTS_ID },
    { category: "Trading", desc: "Stainless steel fasteners, mixed lot", qty: [1, 4], unit: [60000, 110000], vendor: ids.VENDOR_ORIENT_IMPORTS_ID },
    { category: "Trading", desc: "Industrial bearings consignment", qty: [1, 3], unit: [95000, 150000], vendor: ids.VENDOR_ORIENT_IMPORTS_ID },
    { category: "Logistics", desc: "Customs clearance & port handling, JNPT", qty: [1, 3], unit: [45000, 95000], vendor: V.COASTAL_FREIGHT },
    { category: "Logistics", desc: "Inland freight to Pune warehouse", qty: [1, 4], unit: [28000, 52000], vendor: V.COASTAL_FREIGHT },
  ],
  [ids.DIVISION_DOMESTIC_SALES_ID]: [
    { category: "Packaging", desc: "Corrugated cartons, 5-ply (per 1,000)", qty: [2, 10], unit: [14000, 19000], vendor: V.SUNRISE_PACK },
    { category: "Packaging", desc: "Stretch wrap rolls, 500 mm", qty: [20, 80], unit: [450, 700], vendor: V.SUNRISE_PACK },
    { category: "Trading", desc: "Distributor stock replenishment", qty: [1, 3], unit: [90000, 160000], vendor: ids.VENDOR_DELTA_TRADING_ID },
    { category: "Marketing", desc: "Trade fair booth, Mumbai Expo", qty: [1, 1], unit: [180000, 260000], vendor: ids.VENDOR_DELTA_TRADING_ID },
    { category: "IT", desc: "CRM seat licences (annual)", qty: [5, 20], unit: [6500, 9000], vendor: V.NIMBUS_KIGT },
  ],
};

const DIVISIONS = [
  { id: ids.DIVISION_PLANT_OPS_ID, company: ids.COMPANY_KIGM_ID, code: "KIGM", requesters: [ids.USER_PRIYA_ID, ids.USER_PRIYA_ID, ids.USER_PRIYA_ID, U.KABIR, U.KABIR, ids.USER_RAHUL_ID], manager: ids.USER_RAHUL_ID, weight: 1.0 },
  { id: ids.DIVISION_QUALITY_ID, company: ids.COMPANY_KIGM_ID, code: "KIGM", requesters: [U.ANANYA, U.ANANYA, U.ANANYA, U.VIKRAM], manager: U.VIKRAM, weight: 0.45 },
  { id: ids.DIVISION_IMPORT_DESK_ID, company: ids.COMPANY_KIGT_ID, code: "KIGT", requesters: [U.SANA, U.SANA, U.SANA, U.DEV], manager: U.DEV, weight: 0.6 },
  { id: ids.DIVISION_DOMESTIC_SALES_ID, company: ids.COMPANY_KIGT_ID, code: "KIGT", requesters: [U.ISHAAN, U.ISHAAN, U.ISHAAN, U.NISHA], manager: U.NISHA, weight: 0.5 },
];

const JUSTIFICATIONS: Record<string, string[]> = {
  "Raw Materials": ["Stock below reorder level for the next production run.", "Confirmed customer order needs material by month end.", "Planned build for the Q-end dispatch schedule."],
  Equipment: ["Existing units worn beyond tolerance.", "Required for the new fixture line.", "Replacement for equipment that failed calibration."],
  Maintenance: ["Belt showing edge wear flagged in last PM inspection.", "Preventive replacement ahead of peak season."],
  Safety: ["Annual PPE replacement cycle.", "New joiners on the shop floor this month.", "Audit observation: replace damaged gear."],
  Consumables: ["Monthly consumption refill.", "Consumption up with the added second shift."],
  IT: ["Licences expiring this quarter.", "Replacing paper checklists on the inspection line."],
  Trading: ["Firm order from key distributor.", "Replenishment against the forecast.", "Price locked with supplier for this month."],
  Logistics: ["Inbound consignment arriving this week.", "Recurring freight for warehouse transfers."],
  Packaging: ["Packaging stock for the upcoming dispatch cycle.", "Switching to 5-ply for export cartons."],
  Marketing: ["Booth booking for the annual trade fair; early-bird pricing ends soon."],
};

const RETURN_COMMENTS = ["Please attach at least two vendor quotes.", "Quantity looks high vs last quarter - please recheck.", "Split this into capex and opex lines, please."];
const REJECT_COMMENTS = ["Not in this quarter's budget.", "Duplicate of an earlier request.", "Existing stock is sufficient - reuse from store."];
const FINANCE_REJECT_COMMENTS = ["Budget for this head is exhausted for the quarter.", "Please defer to next quarter."];
const PAYMENT_TERMS = ["Net 30", "Net 45", "Net 15", "50% advance, 50% on delivery", "Net 60"];

// ---------- generation ----------
type PRRow = typeof purchaseRequests.$inferInsert;
type PORow = typeof purchaseOrders.$inferInsert;
type HistRow = typeof workflowHistory.$inferInsert;
type AuditRow = typeof auditLog.$inferInsert;

const PR_PREFIX = "80000000";
const PO_PREFIX = "81000000";
const HISTORY_DAYS = 180;

function atWorkHour(t: number) {
  // Nudge a timestamp into Indian working hours (roughly 09:30-18:30 IST).
  const d = new Date(t);
  d.setUTCHours(int(4, 12), int(0, 59), int(0, 59), 0);
  return d.getTime();
}

function generate(now: number) {
  const prs: (PRRow & { submittedAt: number })[] = [];
  const pos: PORow[] = [];
  const history: HistRow[] = [];
  const audit: AuditRow[] = [];
  let prSeq = 0;
  let poSeq = 0;

  for (let daysAgo = HISTORY_DAYS; daysAgo >= 0; daysAgo--) {
    const day = now - daysAgo * DAY;
    const dow = new Date(day).getUTCDay();
    if (dow === 0) continue; // no Sunday submissions
    // Volume ramps up over the period, so the trend chart shows growth.
    const ramp = 0.55 + 0.75 * (1 - daysAgo / HISTORY_DAYS);
    for (const div of DIVISIONS) {
      const expected = div.weight * ramp * (dow === 6 ? 0.3 : 1);
      let count = Math.floor(expected) + (chance(expected - Math.floor(expected)) ? 1 : 0);
      if (chance(0.12)) count++;
      for (let k = 0; k < count; k++) {
        const submittedAt = atWorkHour(day);
        if (submittedAt > now) continue;
        const item = pick(CATALOG[div.id]);
        const unit = Math.round(between(item.unit[0], item.unit[1]) / 50) * 50;
        let qty = int(item.qty[0], item.qty[1]);
        // Keep below the dual-finance-approval threshold (5,00,000) so
        // single-approver flows stay coherent with one Finance Approver.
        while (qty > 1 && qty * unit > 480000) qty--;
        const amount = qty * unit;
        const requester = pick(div.requesters);
        const id = uid(PR_PREFIX, ++prSeq);

        // Walk the state machine; stop when the next step would be in the future.
        let status: PRRow["status"] = "PENDING_DIVISION_APPROVAL";
        let t = submittedAt;
        const hist = (actor: string, role: string, from: string, to: string, at: number, comment?: string) =>
          history.push({ entityType: "PURCHASE_REQUEST", entityId: id, actorId: actor, roleActedAs: role, fromStatus: from, toStatus: to, comment: comment ?? null, createdAt: new Date(at) });
        const aud = (actor: string, action: string, at: number, after: Record<string, unknown>) =>
          audit.push({ actorId: actor, action, entityType: "purchase_requests", entityId: id, companyId: div.company, divisionId: div.id, afterState: JSON.stringify(after), createdAt: new Date(at) });

        // The app records every submit/withdraw as "Employee", even when a
        // Division Manager raises the request - mirror that exactly.
        const requesterRole = "Employee";
        hist(requester, requesterRole, "DRAFT", "PENDING_DIVISION_APPROVAL", t);
        aud(requester, "PR_SUBMITTED", t, { status: "PENDING_DIVISION_APPROVAL", amount: String(amount) });

        // Occasionally a step stalls for days - that's what keeps queues non-empty.
        const delay = (min: number, max: number) => (chance(0.3) ? between(2, 14) : between(min, max)) * DAY;

        const step = (() => {
          if (chance(0.04)) {
            const at = t + between(0.2, 2) * DAY;
            if (at > now) return;
            hist(requester, requesterRole, "PENDING_DIVISION_APPROVAL", "WITHDRAWN", at);
            aud(requester, "PR_WITHDRAWN", at, { status: "WITHDRAWN" });
            status = "WITHDRAWN";
            t = at;
            return;
          }
          // Division
          const dAt = t + delay(0.1, 2.5);
          if (dAt > now) return;
          const roll = rand();
          if (roll < 0.07) {
            hist(div.manager, "Division Manager", "PENDING_DIVISION_APPROVAL", "REJECTED", dAt, pick(REJECT_COMMENTS));
            aud(div.manager, "PR_DIVISION_REJECT", dAt, { status: "REJECTED" });
            status = "REJECTED";
            t = dAt;
            return;
          }
          if (roll < 0.13) {
            hist(div.manager, "Division Manager", "PENDING_DIVISION_APPROVAL", "RETURNED_FOR_REVISION", dAt, pick(RETURN_COMMENTS));
            aud(div.manager, "PR_DIVISION_RETURN", dAt, { status: "RETURNED_FOR_REVISION" });
            status = "RETURNED_FOR_REVISION";
            t = dAt;
            return;
          }
          hist(div.manager, "Division Manager", "PENDING_DIVISION_APPROVAL", "PENDING_FINANCE_APPROVAL", dAt, chance(0.3) ? "Approved." : undefined);
          aud(div.manager, "PR_DIVISION_APPROVE", dAt, { status: "PENDING_FINANCE_APPROVAL" });
          status = "PENDING_FINANCE_APPROVAL";
          t = dAt;

          // Finance
          const fAt = t + delay(0.2, 2.5);
          if (fAt > now) return;
          if (chance(0.06)) {
            hist(ids.USER_MEERA_ID, "Finance Approver", "PENDING_FINANCE_APPROVAL", "REJECTED", fAt, pick(FINANCE_REJECT_COMMENTS));
            aud(ids.USER_MEERA_ID, "PR_FINANCE_REJECT", fAt, { status: "REJECTED" });
            status = "REJECTED";
            t = fAt;
            return;
          }
          hist(ids.USER_MEERA_ID, "Finance Approver", "PENDING_FINANCE_APPROVAL", "APPROVED_PENDING_PO", fAt);
          aud(ids.USER_MEERA_ID, "PR_FINANCE_APPROVE", fAt, { status: "APPROVED_PENDING_PO" });
          status = "APPROVED_PENDING_PO";
          t = fAt;

          // Purchase order
          const pAt = t + delay(0.3, 3);
          if (pAt > now) return;
          const poId = uid(PO_PREFIX, ++poSeq);
          const leadDays = int(5, 21);
          const deliveryDate = new Date(pAt + leadDays * DAY).toISOString().slice(0, 10);
          let poStatus: PORow["status"] = "ISSUED";
          let poUpdated = pAt;
          const poHist = (from: string, to: string, at: number) =>
            history.push({ entityType: "PURCHASE_ORDER", entityId: poId, actorId: ids.USER_ARJUN_ID, roleActedAs: "Procurement Officer", fromStatus: from, toStatus: to, createdAt: new Date(at) });
          const poAud = (action: string, at: number, after: Record<string, unknown>) =>
            audit.push({ actorId: ids.USER_ARJUN_ID, action, entityType: "purchase_orders", entityId: poId, companyId: div.company, divisionId: action === "PO_ISSUED" ? div.id : null, afterState: JSON.stringify(after), createdAt: new Date(at) });

          poHist("APPROVED_PENDING_PO", "PO_ISSUED", pAt);
          poAud("PO_ISSUED", pAt, { status: "ISSUED", vendorId: item.vendor, amount: String(amount) });
          status = "PO_ISSUED";
          t = pAt;

          const delAt = pAt + (leadDays + between(-2, 3)) * DAY;
          if (delAt <= now) {
            poHist("ISSUED", "DELIVERED", delAt);
            poAud("PO_DELIVERED", delAt, { status: "DELIVERED" });
            poStatus = "DELIVERED";
            poUpdated = delAt;
            const cAt = delAt + between(1, 7) * DAY;
            if (cAt <= now) {
              poHist("DELIVERED", "CLOSED", cAt);
              poAud("PO_CLOSED", cAt, { status: "CLOSED" });
              poStatus = "CLOSED";
              poUpdated = cAt;
            }
          }
          pos.push({
            id: poId,
            prId: id,
            vendorId: item.vendor,
            companyId: div.company,
            amount: String(amount),
            deliveryDate,
            paymentTerms: pick(PAYMENT_TERMS),
            status: poStatus,
            issuedBy: ids.USER_ARJUN_ID,
            createdAt: new Date(pAt),
            updatedAt: new Date(poUpdated),
          });
        });
        step();

        prs.push({
          id,
          companyId: div.company,
          divisionId: div.id,
          requesterId: requester,
          category: item.category,
          itemDescription: item.desc,
          quantity: String(qty),
          estimatedUnitCost: String(unit),
          amount: String(amount),
          justification: pick(JUSTIFICATIONS[item.category] ?? ["Operational requirement."]),
          status,
          createdAt: new Date(submittedAt - between(0.02, 0.2) * DAY),
          updatedAt: new Date(t),
          submittedAt,
        });
      }
    }
  }

  // A couple of unsubmitted drafts so "My Requests" shows the full lifecycle.
  for (const [desc, qty, unit] of [
    ["Shop-floor LED high-bay lights", 12, 5400],
    ["Spare air filter cartridges, compressor 3", 8, 1850],
  ] as const) {
    prs.push({
      id: uid(PR_PREFIX, ++prSeq),
      companyId: ids.COMPANY_KIGM_ID,
      divisionId: ids.DIVISION_PLANT_OPS_ID,
      requesterId: ids.USER_PRIYA_ID,
      category: "Maintenance",
      itemDescription: desc,
      quantity: String(qty),
      estimatedUnitCost: String(unit),
      amount: String(qty * unit),
      justification: "Draft - collecting quotes.",
      status: "DRAFT",
      createdAt: new Date(now - between(0.5, 3) * DAY),
      updatedAt: new Date(now - between(0.1, 0.4) * DAY),
      submittedAt: Number.POSITIVE_INFINITY,
    });
  }

  return { prs, pos, history, audit };
}

// Allocate a contiguous block of document numbers in one atomic upsert, the
// same counter the app's allocateNumber() uses - so seeded numbers never
// collide with ones handed out through the UI.
async function allocateBlock(tx: Parameters<Parameters<typeof db.transaction>[0]>[0], companyId: string, name: "PR" | "PO", n: number) {
  if (n === 0) return 0;
  const year = new Date().getFullYear();
  const [row] = await tx
    .insert(companySequences)
    .values({ companyId, sequenceName: name, calendarYear: year, lastValue: n })
    .onConflictDoUpdate({
      target: [companySequences.companyId, companySequences.sequenceName, companySequences.calendarYear],
      set: { lastValue: dsql`${companySequences.lastValue} + ${n}` },
    })
    .returning({ lastValue: companySequences.lastValue });
  return row.lastValue - n + 1; // first number in the block
}

async function insertChunked<T>(rows: T[], insert: (chunk: T[]) => Promise<unknown>, size = 400) {
  for (let i = 0; i < rows.length; i += size) await insert(rows.slice(i, i + size));
}

async function main() {
  const reset = process.argv.includes("--reset");
  const year = new Date().getFullYear();

  // 1. People + vendors (idempotent)
  const passwordHash = await bcrypt.hash(ids.DEMO_PASSWORD, 10);
  const inserted = await db
    .insert(users)
    .values(EXTRA_USERS.map((u) => ({ id: u.id, name: u.name, email: u.email, passwordHash })))
    .onConflictDoNothing()
    .returning({ id: users.id });
  const newIds = new Set(inserted.map((r) => r.id));
  for (const u of EXTRA_USERS.filter((x) => newIds.has(x.id))) {
    await db.insert(userCompanyAccess).values({ userId: u.id, companyId: u.company }).onConflictDoNothing();
    await db.insert(userDivisionAccess).values({ userId: u.id, divisionId: u.division }).onConflictDoNothing();
    await db
      .insert(userRoles)
      .values(
        u.manager
          ? { userId: u.id, roleId: ids.ROLE_DIVISION_MANAGER_ID, companyId: u.company, divisionId: u.division }
          : { userId: u.id, roleId: ids.ROLE_EMPLOYEE_ID }
      )
      .onConflictDoNothing();
  }
  await db.insert(vendors).values(EXTRA_VENDORS).onConflictDoNothing();
  console.log(`Colleagues: ${inserted.length} added, vendors ensured.`);

  // 2. Transaction history
  const seededPRs = await db.select({ id: purchaseRequests.id }).from(purchaseRequests).where(like(dsql`${purchaseRequests.id}::text`, `${PR_PREFIX}-%`));
  if (seededPRs.length > 0 && !reset) {
    console.log(`Demo history already present (${seededPRs.length} requests). Use --reset to regenerate.`);
    return;
  }

  const { prs, pos, history, audit } = generate(Date.now());

  await db.transaction(async (tx) => {
    if (seededPRs.length > 0) {
      const prIds = seededPRs.map((r) => r.id);
      const seededPOs = await tx.select({ id: purchaseOrders.id }).from(purchaseOrders).where(inArray(purchaseOrders.prId, prIds));
      const entityIds = [...prIds, ...seededPOs.map((r) => r.id)];
      await tx.delete(auditLog).where(inArray(auditLog.entityId, entityIds));
      await tx.delete(workflowHistory).where(inArray(workflowHistory.entityId, entityIds));
      await tx.delete(purchaseOrders).where(inArray(purchaseOrders.prId, prIds));
      await tx.delete(purchaseRequests).where(inArray(purchaseRequests.id, prIds));
      // Rewind each counter to the highest number still in use, so repeated
      // resets don't leave the demo numbering at KIGM-PR-2026-00700.
      const prefix = `%-${year}-%`;
      await tx.execute(dsql`
        update company_sequences cs set last_value = coalesce((
          select max(split_part(pr.pr_number, '-', 4)::int) from purchase_requests pr
          where pr.company_id = cs.company_id and pr.pr_number like ${prefix}), 0)
        where cs.sequence_name = 'PR' and cs.calendar_year = ${year}`);
      await tx.execute(dsql`
        update company_sequences cs set last_value = coalesce((
          select max(split_part(po.po_number, '-', 4)::int) from purchase_orders po
          where po.company_id = cs.company_id and po.po_number like ${prefix}), 0)
        where cs.sequence_name = 'PO' and cs.calendar_year = ${year}`);
      console.log(`Reset: removed ${prIds.length} requests and ${seededPOs.length} orders; counters rewound.`);
    }

    // Number in chronological order, per company, like the live app would have.
    for (const [companyId, code] of [
      [ids.COMPANY_KIGM_ID, "KIGM"],
      [ids.COMPANY_KIGT_ID, "KIGT"],
    ] as const) {
      const submitted = prs.filter((p) => p.companyId === companyId && p.status !== "DRAFT").sort((a, b) => a.submittedAt - b.submittedAt);
      let n = await allocateBlock(tx, companyId, "PR", submitted.length);
      for (const p of submitted) p.prNumber = `${code}-PR-${year}-${String(n++).padStart(5, "0")}`;

      const companyPOs = pos.filter((p) => p.companyId === companyId).sort((a, b) => a.createdAt!.getTime() - b.createdAt!.getTime());
      let m = await allocateBlock(tx, companyId, "PO", companyPOs.length);
      for (const p of companyPOs) p.poNumber = `${code}-PO-${year}-${String(m++).padStart(5, "0")}`;
    }

    await insertChunked(
      prs.map(({ submittedAt: _s, ...p }) => p),
      (c) => tx.insert(purchaseRequests).values(c)
    );
    await insertChunked(pos, (c) => tx.insert(purchaseOrders).values(c));
    await insertChunked(history, (c) => tx.insert(workflowHistory).values(c));
    await insertChunked(audit, (c) => tx.insert(auditLog).values(c));
  });

  const byStatus = prs.reduce<Record<string, number>>((acc, p) => ((acc[p.status!] = (acc[p.status!] ?? 0) + 1), acc), {});
  console.log(`Seeded ${prs.length} requests, ${pos.length} purchase orders, ${audit.length} audit events.`);
  console.table(byStatus);
  console.log("New logins (password " + ids.DEMO_PASSWORD + "): " + EXTRA_USERS.map((u) => u.email).join(", "));
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await sql.end();
  });
